#pragma once
#include <pebble.h>
#include "flux.h"

enum STORAGE_KEYS {
	STORAGE_SETTINGS,
	STORAGE_STATE_TIME,
	STORAGE_INACTIVITY_SHOWN,
	STORAGE_INACTIVITY_PERIOD,
	STORAGE_ACTIVITY_WINDOW
};
enum SETTING_KEYS {
	SETTING_PATTERN_CHANGE,
	SETTING_PATTERN_NODES,
	SETTING_PATTERN_FRACTAL,
	SETTING_ANIMATIONS_FREQUENCY,
	SETTING_ANIMATIONS_DURATION,
	SETTING_COLOURS_BRIGHT,
	SETTING_COLOURS_SOFT,
	SETTING_POWER_START_HOUR,
	SETTING_POWER_START_MINUTE,
	SETTING_POWER_END_HOUR,
	SETTING_POWER_END_MINUTE,
	SETTING_POWER_THRESHOLD,
	SETTING_BLUETOOTH_ICON,
	SETTING_BLUETOOTH_VIBRATE,
	SETTING_INACTIVITY_PERIOD,
	SETTING_INACTIVITY_REPEAT,
	SETTING_INACTIVITY_THRESHOLD,
	SETTING_DISPLAY_DATE,
	SETTING_KEY_COUNT
};

uint8_t get_setting(uint8_t key);
void sync_settings();
void save_settings();
