#pragma once
#include <pebble.h>
#include "flux.h"

enum STORAGE_KEYS {
	STORAGE_SETTINGS
};
enum SETTING_KEYS {
	SETTING_PATTERN_CHANGE,
	SETTING_PATTERN_NODES,
	SETTING_PATTERN_FRACTAL,
	SETTING_ANIMATIONS_FREQUENCY,
	SETTING_ANIMATIONS_DURATION,
	SETTING_COLOURS_BRIGHT,
	SETTING_COLOURS_SOFT,
	SETTING_POWER_START_HOUR,
	SETTING_POWER_START_MINUTE,
	SETTING_POWER_END_HOUR,
	SETTING_POWER_END_MINUTE,
	SETTING_POWER_THRESHOLD,
	SETTING_INACTIVITY_PERIOD,
	SETTING_DISPLAY_DATE,
	SETTING_KEY_COUNT
};

uint8_t get_setting(int key);
void sync_settings();
void save_settings();
